import type { ProjectConfig } from "@/features/configurator/types";

export const makeBaseConfig = (overrides: Partial<ProjectConfig> = {}): ProjectConfig => ({
  projectName: "my-service",
  additionalPackages: [],
  middlewares: [],
  securityStrategies: [],
  observabilityLibs: [],
  packageManager: "npm",
  nodeVersion: "20 LTS",
  framework: "NestJS",
  apiPattern: "REST Express",
  database: "TypeORM",
  databaseEngine: "PostgreSQL",
  migrationsEnabled: true,
  seedEnabled: true,
  linter: "ESLint",
  testLibrary: "Jest",
  logger: "Pino",
  healthcheckEnabled: true,
  documentation: "Swagger Code-first",
  security: "JWT Authentication",
  architecture: "Hexagonal",
  ciCdEnabled: false,
  dockerfileEnabled: false,
  dockerComposeEnabled: false,
  messagingEnabled: false,
  messagingType: null,
  templatePlugins: [],
  environments: ["development", "staging", "production"],
  secretsProvider: "Environment Variables",
  ...overrides,
});
